# Aula 4 - Numpy

In [1]:
import numpy as np

In [2]:
array_1 = np.array([[10,20,30,40],[1,2,3,4]])
array_2 = np.array([[50,60,70,80],[5,6,7,8]])

In [3]:
# Soma
array_1 + array_2

array([[ 60,  80, 100, 120],
       [  6,   8,  10,  12]])

In [4]:
# Multipliacao
array_1 * array_2

array([[ 500, 1200, 2100, 3200],
       [   5,   12,   21,   32]])

In [5]:
# Divisao
1 / array_1

array([[0.1       , 0.05      , 0.03333333, 0.025     ],
       [1.        , 0.5       , 0.33333333, 0.25      ]])

In [6]:
# Slice
array_3 = np.array([1,2,3,4,5,6,7,8,9,10])

In [7]:
array_3[1:3]

array([2, 3])

In [8]:
array_3[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
array_3[:3]

array([1, 2, 3])

In [10]:
array_3[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Desafio 1
Supondo que uma imagem é composta por uma matriz 4 x 4, mapeie as letras a, d e j conforme a figura abaixo, sendo a cor cinza representada pelo bit 1 e a branca pelo bit 0.  
Para inicializar as matrizes opte pelas estruturas np.ones e np.zeros.  
Utilize a anotação slice.

In [11]:
import numpy
letra_a = np.zeros([4,4])
letra_a[0,1:3] = 1 
letra_a[1,0] = 1 
letra_a[1,3] = 1 
letra_a[2:3] = 1 
letra_a[3,0] = 1 
letra_a[3,3] = 1 
letra_a

array([[0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.],
       [1., 0., 0., 1.]])

In [12]:
letra_d = np.zeros([4,4])
letra_d[0,:3] = 1 
letra_d[1,0] = 1 
letra_d[1,3] = 1 
letra_d[2,0] = 1 
letra_d[2,3] = 1
letra_d[3,:3] = 1
letra_d

array([[1., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 0.]])

In [13]:
letra_j = np.zeros([4,4])
letra_j[0,:] = 1 
letra_j[1,2:3] = 1 
letra_j[2,0] = 1 
letra_j[2,2] = 1 
letra_j[3,:3] = 1
letra_j

array([[1., 1., 1., 1.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 1., 1., 0.]])

## Desafio 2
Utilize o arquivo "iris.data.txt” (no repositório) que contem os dados do projeto Íris, em partilar o tamanho das sépalas, para normalizar seus dados, de tal forma que os valores fiquem entre 0 e 1.

In [14]:
import numpy as np

In [34]:
array_norm = np.loadtxt('iris.txt', delimiter=',', usecols=[0])
# Normalizando
max = array_texto.max()
min = array_texto.min()
norm = lambda x: (x - min)/(max - min)
a = np.array(list(map(norm,array_norm)))
a

array([0.22222222, 0.16666667, 0.11111111, 0.08333333, 0.19444444,
       0.30555556, 0.08333333, 0.19444444, 0.02777778, 0.16666667,
       0.30555556, 0.13888889, 0.13888889, 0.        , 0.41666667,
       0.38888889, 0.30555556, 0.22222222, 0.38888889, 0.22222222,
       0.30555556, 0.22222222, 0.08333333, 0.22222222, 0.13888889,
       0.19444444, 0.19444444, 0.25      , 0.25      , 0.11111111,
       0.13888889, 0.30555556, 0.25      , 0.33333333, 0.16666667,
       0.19444444, 0.33333333, 0.16666667, 0.02777778, 0.22222222,
       0.19444444, 0.05555556, 0.02777778, 0.19444444, 0.22222222,
       0.13888889, 0.22222222, 0.08333333, 0.27777778, 0.19444444,
       0.75      , 0.58333333, 0.72222222, 0.33333333, 0.61111111,
       0.38888889, 0.55555556, 0.16666667, 0.63888889, 0.25      ,
       0.19444444, 0.44444444, 0.47222222, 0.5       , 0.36111111,
       0.66666667, 0.36111111, 0.41666667, 0.52777778, 0.36111111,
       0.44444444, 0.5       , 0.55555556, 0.5       , 0.58333

In [38]:
# Solucao do professor
array = np.loadtxt('iris.txt', delimiter=',', usecols=[0])
max, min = array.max(), array.min()
max, min

(7.9, 4.3)

In [42]:
array_norm = (array_norm - min)/(max - min)
array_norm

array([-1.6136355 , -1.61482625, -1.61601699, -1.61661237, -1.61423087,
       -1.61184938, -1.61661237, -1.61423087, -1.61780312, -1.61482625,
       -1.61184938, -1.61542162, -1.61542162, -1.61839849, -1.60946788,
       -1.61006325, -1.61184938, -1.6136355 , -1.61006325, -1.6136355 ,
       -1.61184938, -1.6136355 , -1.61661237, -1.6136355 , -1.61542162,
       -1.61423087, -1.61423087, -1.61304012, -1.61304012, -1.61601699,
       -1.61542162, -1.61184938, -1.61304012, -1.611254  , -1.61482625,
       -1.61423087, -1.611254  , -1.61482625, -1.61780312, -1.6136355 ,
       -1.61423087, -1.61720774, -1.61780312, -1.61423087, -1.6136355 ,
       -1.61542162, -1.6136355 , -1.61661237, -1.61244475, -1.61423087,
       -1.60232339, -1.60589563, -1.60291876, -1.611254  , -1.60530026,
       -1.61006325, -1.60649101, -1.61482625, -1.60470488, -1.61304012,
       -1.61423087, -1.6088725 , -1.60827713, -1.60768176, -1.61065863,
       -1.60410951, -1.61065863, -1.60946788, -1.60708638, -1.61

# Aula 4 - Pandas

In [53]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
import webbrowser
site ="https://pt.wikipedia.org/wiki/Lista_de_episódios_de_Daredevil"
webbrowser.open(site)
breaking_bad_temporada_4 = pd.read_clipboard()
breaking_bad_temporada_4

True

In [50]:
None